#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov  2 22:24:35 2018

@author: r17935avinash
"""

import torch 
from keras.datasets import mnist
import matplotlib.pyplot as plt
import numpy as np

##tensorflow is shit

batch_size=int(60000/128)
epochs=5

def convert(X):
    X=X.reshape(X.shape[0],784)
    return torch.from_numpy(X)


def model_accuracy(model,X,y):
    pred=model(X.float())
    total=0
    correct=0
    _, predicted = torch.max(pred.data, 1)
    total += y.size(0)
    correct += (predicted == y.long()).sum().item()
    return (correct/total)*100
    

model=torch.nn.Sequential(
        torch.nn.Linear(784,256),
        torch.nn.ReLU(),
        torch.nn.Linear(256,10))



(X_train,y_train),(X_test,y_test)=mnist.load_data()

X_train=convert(X_train)
X_test=convert(X_test)
y_train=torch.from_numpy(y_train)
y_test=torch.from_numpy(y_test)


criterion=torch.nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=0.001)

for i in range(epochs):
    
    
    
    for current in range(128):
        temp_train=X_train[current*(batch_size):(current+1)*batch_size]
        temp_label=y_train[current*(batch_size):(current+1)*batch_size]
        output=model(temp_train.float())
        model.zero_grad()
        loss=criterion(output,temp_label.long())
        loss.backward()
        optimizer.step()
    print("Epoch::",i+1)
    print("Training Loss after epoch",i+1,"is ",loss.item())
    print("Training model accuracy is ",model_accuracy(model,X_train,y_train))
    print("Test model accuracy is ",model_accuracy(model,X_test,y_test))
    print("___________________________________________________")
    
for i in range(5):
    plt.imshow(X_test[i].reshape(28,28))
    result=model(X_test[i].float())
    result=result.data.numpy()
    print("The Digit is",np.argmax(result))
    plt.show()
    
    
"""Output 
Epoch:: 1
Training Loss after epoch 1 is  0.2724051773548126
Training model accuracy is  94.11333333333334
Test model accuracy is  93.56
___________________________________________________
Epoch:: 2
Training Loss after epoch 2 is  0.16064175963401794
Training model accuracy is  96.39
Test model accuracy is  95.0
___________________________________________________
Epoch:: 3
Training Loss after epoch 3 is  0.12786202132701874
Training model accuracy is  97.68166666666667
Test model accuracy is  95.78999999999999
___________________________________________________
Epoch:: 4
Training Loss after epoch 4 is  0.08434204012155533
Training model accuracy is  98.15833333333333
Test model accuracy is  95.96000000000001
___________________________________________________
Epoch:: 5
Training Loss after epoch 5 is  0.05189462751150131
Training model accuracy is  98.46833333333333
Test model accuracy is  96.05
___________________________________________________"""




    
    
    
    
    
    
